apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
spec:
  initContainers:
    - image: ubuntu
      name: init-demo
      command:
        - "ls"
      args:
        - "-l"
  containers:
    - image: nginx
      name: nginx
      ports:
        - name: nginx-port
          containerPort: 80
          hostPort: 8090
          protocol: TCP
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-data
      resources:
        limits:
          cpu: "200m"
          memory: "200Mi"
        requests:
          cpu: "100m"
          memory: "100Mi"

    - image: ubuntu:22.04
      name: ubuntu
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: /var/tmp
          name: nginx-data
      resources:
        limits:
          cpu: "200m"
          memory: "200Mi"
        requests:
          cpu: "100m"
          memory: "100Mi"
  volumes:
    - name: nginx-data
      emptyDir: {}        