apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
          name: web
      volumeMounts:
        - name: nfs-vol
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: nfs-vol
      persistentVolumeClaim:
        claimName: nfs-pvc