apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: nfs-manual 
  accessModes:
    - ReadWriteMany
  #persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  nfs:
    path: /mnt/nfs_backup
    server: 192.168.0.123
    readOnly: false  
  