apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cronjob
spec:
  successfulJobsHistoryLimit: 10
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - "/bin/sh"
                - -c
                - date; echo from the kubernetes cluster
          restartPolicy: Never      