apiVersion: v1
kind: Pod
metadata: 
  name: test-demo
spec:
  containers:
    - name: nginx
      image: nginx
      command: [ "/bin/sh", "-c", "ls /etc/config/ && cat /etc/config/mysql_root_password" ]
      volumeMounts:
        - name: volume-demo
          mountPath: /etc/config
  volumes:
    - name: volume-demo
      configMap:
        name: db-data 
        defaultMode: 0755
  restartPolicy: Never