apiVersion: v1
kind: Pod
metadata:
  name: secret-docker
spec:
  # imagePullSecrets:
  #   - name: my-secrets
  containers:
    - name: nginx-demo 
      image: 026678532386.dkr.ecr.us-east-1.amazonaws.com/nginx-demo:latest
      command: ["bin/sh"]
      args: ["-c", "sleep 5000"]
      ports:
        - containerPort: 80