apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: mycontainer
      image: redis
      command: ["/bin/sh", "-c", "printenv"]
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: mysql_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql_root_password
              name: db-credentials
  restartPolicy: Never