apiVersion: v1
kind: Pod
metadata:
  name: secret-docker
spec:
  imagePullSecrets:
    - name: my-secrets
  containers:
    - name: 1st
      image: sruthi2022/nginx-demo-image:v1.0
      command: ["bin/sh"]
      args: ["-c", "sleep 5000"]