apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-temp
  template:
    metadata:
      labels:
        app: nginx-temp
    spec:
      containers:
        - name: container-writing-dates
          image: alpine
          command: ["/bin/sh"]
          args: ["-c", "while true; do date >> /var/log/index.html; sleep 10;done"]
          volumeMounts:
            - name: shared-date-logs
              mountPath: /var/log       
        - name: container-serving-dates
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-date-logs
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: shared-date-logs
          emptyDir: {}
            
