apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeName: ip-192-168-194-5.ec2.internal
      containers:
        - name: jenkins
          image: jenkins/jenkins:latest
          ports:
            - name: jenkins-port
              containerPort: 8080
              hostPort: 8090
            - name: slave-pprt
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home    
      volumes:
        - name: jenkins-home
          hostPath:
            path: /jenkins-data
            type: DirectoryOrCreate