apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: task-pv-claim
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: nginx-temp
  template:
    metadata:
      labels:
        app: nginx-temp
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: task-pv-storage
              mountPath: "/usr/share/nginx/html"  
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim