apiVersion: v1
kind: Pod
metadata:
  name: demo-pv-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - name: demo-pv-storage
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: demo-pv-storage
      persistentVolumeClaim:
        claimName: pv-claim-hostpath
