apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
 # persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/tmp/data"