apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-temp
spec:
  selector:
    app: mysql-temp
    tier: mysql
  
  ports:
    - port: 3306
      targetPort: 3306
      